FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY VitalFlow.His.Api.csproj ./
RUN dotnet restore VitalFlow.His.Api.csproj

COPY . ./
RUN dotnet publish VitalFlow.His.Api.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "VitalFlow.His.Api.dll"]
