-- 033 - Catalogo de provincias y localidades para direcciones

create schema if not exists sch_ubicacion;

create table if not exists sch_ubicacion.provincia (
    id          varchar(5)    primary key,
    nombre      varchar(120)  not null,
    pais        varchar(60)   not null default 'Argentina',
    activo      boolean       not null default true,
    created_at  timestamptz   not null default now(),
    updated_at  timestamptz   not null default now()
);

create index if not exists idx_provincia_nombre on sch_ubicacion.provincia (upper(nombre));

create table if not exists sch_ubicacion.localidad (
    id           varchar(10)   primary key,
    provincia_id varchar(5)    not null references sch_ubicacion.provincia(id),
    nombre       varchar(200)  not null,
    activo       boolean       not null default true,
    created_at   timestamptz   not null default now(),
    updated_at   timestamptz   not null default now()
);

create index if not exists idx_localidad_provincia on sch_ubicacion.localidad (provincia_id, upper(nombre));

comment on table sch_ubicacion.provincia is 'Provincias argentinas';
comment on table sch_ubicacion.localidad is 'Localidades/ciudades argentinas';

-- Provincias
insert into sch_ubicacion.provincia (id, nombre) values
    ('BA',  'Buenos Aires'),
    ('CABA','Ciudad Autonoma de Buenos Aires'),
    ('CAT', 'Catamarca'),
    ('CHA', 'Chaco'),
    ('CHU', 'Chubut'),
    ('COR', 'Cordoba'),
    ('CTE', 'Corrientes'),
    ('ER',  'Entre Rios'),
    ('FOR', 'Formosa'),
    ('JUJ', 'Jujuy'),
    ('LP',  'La Pampa'),
    ('LR',  'La Rioja'),
    ('MZA', 'Mendoza'),
    ('MIS', 'Misiones'),
    ('NQN', 'Neuquen'),
    ('RN',  'Rio Negro'),
    ('SAL', 'Salta'),
    ('SJ',  'San Juan'),
    ('SL',  'San Luis'),
    ('SC',  'Santa Cruz'),
    ('SF',  'Santa Fe'),
    ('SDE', 'Santiago del Estero'),
    ('TF',  'Tierra del Fuego'),
    ('TUC', 'Tucuman')
on conflict (id) do update set nombre = excluded.nombre;

-- Localidades principales por provincia
insert into sch_ubicacion.localidad (id, provincia_id, nombre) values
    ('BA001', 'BA',  'La Plata'),
    ('BA002', 'BA',  'Mar del Plata'),
    ('BA003', 'BA',  'Bahia Blanca'),
    ('BA004', 'BA',  'Quilmes'),
    ('BA005', 'BA',  'San Isidro'),
    ('BA006', 'BA',  'Avellaneda'),
    ('BA007', 'BA',  'Lanus'),
    ('BA008', 'BA',  'Lomas de Zamora'),
    ('BA009', 'BA',  'Moron'),
    ('BA010', 'BA',  'Tandil'),
    ('BA011', 'BA',  'Pergamino'),
    ('BA012', 'BA',  'Junin'),
    ('BA013', 'BA',  'San Nicolas de los Arroyos'),
    ('BA014', 'BA',  'Zarate'),
    ('BA015', 'BA',  'Campana'),
    ('BA016', 'BA',  'Pilar'),
    ('BA017', 'BA',  'Escobar'),
    ('BA018', 'BA',  'Tigre'),
    ('BA019', 'BA',  'San Fernando'),
    ('BA020', 'BA',  'Vicente Lopez'),
    ('BA021', 'BA',  'La Matanza'),
    ('BA022', 'BA',  'Tres de Febrero'),
    ('BA023', 'BA',  'Almirante Brown'),
    ('BA024', 'BA',  'Florencio Varela'),
    ('BA025', 'BA',  'Berazategui'),
    ('BA026', 'BA',  'Ezeiza'),
    ('BA027', 'BA',  'Hurlingham'),
    ('BA028', 'BA',  'Ituzaingo'),
    ('BA029', 'BA',  'Jose C. Paz'),
    ('BA030', 'BA',  'Malvinas Argentinas'),
    ('BA031', 'BA',  'Merlo'),
    ('BA032', 'BA',  'Moreno'),
    ('BA033', 'BA',  'San Miguel'),
    ('BA034', 'BA',  'Necochea'),
    ('BA035', 'BA',  'Olavarria'),
    ('BA036', 'BA',  'Azul'),
    ('BA037', 'BA',  'Chivilcoy'),
    ('BA038', 'BA',  'Lujan'),
    ('BA039', 'BA',  'Mercedes'),
    ('BA040', 'BA',  'Dolores'),
    ('BA041', 'BA',  'Pinamar'),
    ('BA042', 'BA',  'Villa Gesell'),
    ('BA043', 'BA',  'Miramar'),
    ('BA044', 'BA',  'Tornquist'),
    ('BA045', 'BA',  'Coronel Suarez'),
    ('BA046', 'BA',  'Pehuajo'),
    ('BA047', 'BA',  'Trenque Lauquen'),
    ('BA048', 'BA',  'Carlos Casares'),
    ('BA049', 'BA',  '9 de Julio'),
    ('BA050', 'BA', '25 de Mayo'),
    ('BA051', 'BA', 'San Vicente'),
    ('CB001', 'CABA','Comuna 1'),
    ('CB002', 'CABA','Comuna 2'),
    ('CB003', 'CABA','Comuna 3'),
    ('CB004', 'CABA','Comuna 4'),
    ('CB005', 'CABA','Comuna 5'),
    ('CB006', 'CABA','Comuna 6'),
    ('CB007', 'CABA','Comuna 7'),
    ('CB008', 'CABA','Comuna 8'),
    ('CB009', 'CABA','Comuna 9'),
    ('CB010', 'CABA','Comuna 10'),
    ('CB011', 'CABA','Comuna 11'),
    ('CB012', 'CABA','Comuna 12'),
    ('CB013', 'CABA','Comuna 13'),
    ('CB014', 'CABA','Comuna 14'),
    ('CB015', 'CABA','Comuna 15'),
    ('CT001', 'CAT', 'San Fernando del Valle de Catamarca'),
    ('CT002', 'CAT', 'Andalgala'),
    ('CT003', 'CAT', 'Tinogasta'),
    ('CT004', 'CAT', 'Santa Maria'),
    ('CT005', 'CAT', 'Belen'),
    ('CH001', 'CHA', 'Resistencia'),
    ('CH002', 'CHA', 'Barranqueras'),
    ('CH003', 'CHA', 'Presidencia Roque Saenz Pena'),
    ('CH004', 'CHA', 'Villa Angela'),
    ('CH005', 'CHA', 'Charata'),
    ('CH006', 'CHA', 'Las Brenas'),
    ('CH007', 'CHA', 'Castelli'),
    ('CH008', 'CHA', 'Tres Isletas'),
    ('CH009', 'CHA', 'General San Martin'),
    ('CU001', 'CHU', 'Rawson'),
    ('CU002', 'CHU', 'Comodoro Rivadavia'),
    ('CU003', 'CHU', 'Trelew'),
    ('CU004', 'CHU', 'Puerto Madryn'),
    ('CU005', 'CHU', 'Esquel'),
    ('CU006', 'CHU', 'Gaiman'),
    ('CU007', 'CHU', 'Sarmiento'),
    ('CO001', 'COR', 'Cordoba Capital'),
    ('CO002', 'COR', 'Villa Carlos Paz'),
    ('CO003', 'COR', 'Rio Cuarto'),
    ('CO004', 'COR', 'Villa Maria'),
    ('CO005', 'COR', 'San Francisco'),
    ('CO006', 'COR', 'Alta Gracia'),
    ('CO007', 'COR', 'Bell Ville'),
    ('CO008', 'COR', 'Cruz del Eje'),
    ('CO009', 'COR', 'Deán Funes'),
    ('CO010', 'COR', 'Jesus Maria'),
    ('CO011', 'COR', 'La Falda'),
    ('CO012', 'COR', 'Laboulaye'),
    ('CO013', 'COR', 'Marcos Juarez'),
    ('CO014', 'COR', 'Rio Tercero'),
    ('CO015', 'COR', 'Villa Allende'),
    ('CO016', 'COR', 'Arroyito'),
    ('CS001', 'CTE', 'Corrientes Capital'),
    ('CS002', 'CTE', 'Goya'),
    ('CS003', 'CTE', 'Mercedes'),
    ('CS004', 'CTE', 'Curuzu Cuatia'),
    ('CS005', 'CTE', 'Paso de los Libres'),
    ('CS006', 'CTE', 'Esquina'),
    ('CS007', 'CTE', 'Monte Caseros'),
    ('CS008', 'CTE', 'Bella Vista'),
    ('CS009', 'CTE', 'Santo Tome'),
    ('ER001', 'ER',  'Parana'),
    ('ER002', 'ER',  'Concordia'),
    ('ER003', 'ER',  'Gualeguaychu'),
    ('ER004', 'ER',  'Concepcion del Uruguay'),
    ('ER005', 'ER',  'Gualeguay'),
    ('ER006', 'ER',  'Villaguay'),
    ('ER007', 'ER',  'Chajari'),
    ('ER008', 'ER',  'Victoria'),
    ('ER009', 'ER',  'Diamante'),
    ('ER010', 'ER',  'La Paz'),
    ('FO001', 'FOR', 'Formosa Capital'),
    ('FO002', 'FOR', 'Clorinda'),
    ('FO003', 'FOR', 'Pirané'),
    ('FO004', 'FOR', 'El Colorado'),
    ('FO005', 'FOR', 'Ingeniero Juarez'),
    ('JU001', 'JUJ', 'San Salvador de Jujuy'),
    ('JU002', 'JUJ', 'Palpala'),
    ('JU003', 'JUJ', 'Libertador General San Martin'),
    ('JU004', 'JUJ', 'La Quiaca'),
    ('JU005', 'JUJ', 'Humahuaca'),
    ('JU006', 'JUJ', 'Tilcara'),
    ('JU007', 'JUJ', 'Perico'),
    ('LP001', 'LP',  'Santa Rosa'),
    ('LP002', 'LP',  'General Pico'),
    ('LP003', 'LP',  'Toay'),
    ('LP004', 'LP',  'Victorica'),
    ('LP005', 'LP',  'Macachin'),
    ('LP006', 'LP',  'Realico'),
    ('LR001', 'LR',  'La Rioja Capital'),
    ('LR002', 'LR',  'Chilecito'),
    ('LR003', 'LR',  'Aimogasta'),
    ('LR004', 'LR',  'Chepes'),
    ('LR005', 'LR',  'Famatina'),
    ('LR006', 'LR',  'Villa Union'),
    ('MZ001', 'MZA', 'Ciudad de Mendoza'),
    ('MZ002', 'MZA', 'Godoy Cruz'),
    ('MZ003', 'MZA', 'Guaymallen'),
    ('MZ004', 'MZA', 'San Rafael'),
    ('MZ005', 'MZA', 'Lujan de Cuyo'),
    ('MZ006', 'MZA', 'Maipú'),
    ('MZ007', 'MZA', 'Las Heras'),
    ('MZ008', 'MZA', 'Tunuyan'),
    ('MZ009', 'MZA', 'San Martin'),
    ('MZ010', 'MZA', 'Rivadavia'),
    ('MZ011', 'MZA', 'General Alvear'),
    ('MS001', 'MIS', 'Posadas'),
    ('MS002', 'MIS', 'Obera'),
    ('MS003', 'MIS', 'Eldorado'),
    ('MS004', 'MIS', 'Puerto Iguazu'),
    ('MS005', 'MIS', 'San Vicente'),
    ('MS006', 'MIS', 'Apóstoles'),
    ('MS007', 'MIS', 'Leandro N. Alem'),
    ('MS008', 'MIS', 'Montecarlo'),
    ('MS009', 'MIS', 'Aristobulo del Valle'),
    ('NQ001', 'NQN', 'Neuquen Capital'),
    ('NQ002', 'NQN', 'Cipolletti'),
    ('NQ003', 'NQN', 'Centenario'),
    ('NQ004', 'NQN', 'Plottier'),
    ('NQ005', 'NQN', 'San Martin de los Andes'),
    ('NQ006', 'NQN', 'Villa La Angostura'),
    ('NQ007', 'NQN', 'Zapala'),
    ('NQ008', 'NQN', 'Chos Malal'),
    ('NQ009', 'NQN', 'Cutral Co'),
    ('RN001', 'RN',  'Viedma'),
    ('RN002', 'RN',  'General Roca'),
    ('RN003', 'RN',  'San Carlos de Bariloche'),
    ('RN004', 'RN',  'Cipolletti'),
    ('RN005', 'RN',  'El Bolson'),
    ('RN006', 'RN',  'Allen'),
    ('RN007', 'RN',  'Rio Colorado'),
    ('RN008', 'RN',  'Choele Choel'),
    ('RN009', 'RN',  'Chimpay'),
    ('SA001', 'SAL', 'Salta Capital'),
    ('SA002', 'SAL', 'San Ramon de la Nueva Oran'),
    ('SA003', 'SAL', 'Tartagal'),
    ('SA004', 'SAL', 'Cafayate'),
    ('SA005', 'SAL', 'Metan'),
    ('SA006', 'SAL', 'Rosario de la Frontera'),
    ('SA007', 'SAL', 'Güemes'),
    ('SA008', 'SAL', 'Embarcacion'),
    ('SA009', 'SAL', 'San Antonio de los Cobres'),
    ('SJ001', 'SJ',  'San Juan Capital'),
    ('SJ002', 'SJ',  'Rivadavia'),
    ('SJ003', 'SJ',  'Chimbas'),
    ('SJ004', 'SJ',  'Santa Lucia'),
    ('SJ005', 'SJ',  'Rawson'),
    ('SJ006', 'SJ',  'Caucete'),
    ('SJ007', 'SJ',  'Jachal'),
    ('SJ008', 'SJ',  'Albardon'),
    ('SJ009', 'SJ',  'Calingasta'),
    ('SL001', 'SL',  'San Luis Capital'),
    ('SL002', 'SL',  'Villa Mercedes'),
    ('SL003', 'SL',  'Merlo'),
    ('SL004', 'SL',  'La Punta'),
    ('SL005', 'SL',  'Justo Daract'),
    ('SL006', 'SL',  'Tilisarao'),
    ('SL007', 'SL',  'Concarán'),
    ('SC001', 'SC',  'Rio Gallegos'),
    ('SC002', 'SC',  'Caleta Olivia'),
    ('SC003', 'SC',  'El Calafate'),
    ('SC004', 'SC',  'Puerto Deseado'),
    ('SC005', 'SC',  'Pico Truncado'),
    ('SC006', 'SC',  'Las Heras'),
    ('SC007', 'SC',  'San Julian'),
    ('SC008', 'SC',  'Perito Moreno'),
    ('SF001', 'SF',  'Santa Fe Capital'),
    ('SF002', 'SF',  'Rosario'),
    ('SF003', 'SF',  'Rafaela'),
    ('SF004', 'SF',  'Venado Tuerto'),
    ('SF005', 'SF',  'Reconquista'),
    ('SF006', 'SF',  'Villa Constitucion'),
    ('SF007', 'SF',  'San Lorenzo'),
    ('SF008', 'SF',  'Esperanza'),
    ('SF009', 'SF',  'Santo Tome'),
    ('SF010', 'SF',  'Casilda'),
    ('SF011', 'SF',  'Sunchales'),
    ('SF012', 'SF',  'Firmat'),
    ('SF013', 'SF',  'San Justo'),
    ('SF014', 'SF',  'Tostado'),
    ('SE001', 'SDE', 'Santiago del Estero Capital'),
    ('SE002', 'SDE', 'La Banda'),
    ('SE003', 'SDE', 'Termas de Rio Hondo'),
    ('SE004', 'SDE', 'Añatuya'),
    ('SE005', 'SDE', 'Frias'),
    ('SE006', 'SDE', 'Fernandez'),
    ('SE007', 'SDE', 'Monte Quemado'),
    ('SE008', 'SDE', 'Quimili'),
    ('TF001', 'TF',  'Ushuaia'),
    ('TF002', 'TF',  'Rio Grande'),
    ('TF003', 'TF',  'Tolhuin'),
    ('TU001', 'TUC', 'San Miguel de Tucuman'),
    ('TU002', 'TUC', 'Yerba Buena'),
    ('TU003', 'TUC', 'Tafi Viejo'),
    ('TU004', 'TUC', 'Concepcion'),
    ('TU005', 'TUC', 'Aguilares'),
    ('TU006', 'TUC', 'Monteros'),
    ('TU007', 'TUC', 'Famailla'),
    ('TU008', 'TUC', 'Banda del Rio Sali'),
    ('TU009', 'TUC', 'Trancas')
on conflict (id) do update set nombre = excluded.nombre;
