services:
  postgres:
    image: postgres:16-alpine
    container_name: vitalflow-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "55433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    profiles:
      - legacy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./back/src/VitalFlow.His.Api
      dockerfile: Dockerfile
    container_name: vitalflow-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__VitalFlowHisDb: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__SigningKey: ${JWT_SIGNING_KEY}
      Smtp__Host: ${SMTP_HOST}
      Smtp__Port: ${SMTP_PORT}
      Smtp__Username: ${SMTP_USERNAME}
      Smtp__Password: ${SMTP_PASSWORD}
      Smtp__FromAddress: ${SMTP_FROM_ADDRESS}
      Smtp__FromName: ${SMTP_FROM_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:8080"
    profiles:
      - legacy

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vitalflow-frontend
    ports:
      - "5175:80"

volumes:
  pgdata:
