openapi: 3.0.3
info:
  title: VitalFlow HIS Agenda API
  version: 1.0.0
paths:
  /api/v1/agendas:
    get:
      summary: Lista agendas
      responses:
        '200':
          description: OK
    post:
      summary: Crea agenda
      responses:
        '201':
          description: Creada
  /api/v1/agendas/{agendaId}/bloques:
    post:
      summary: Agrega bloque de programacion
      parameters:
        - name: agendaId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Aceptado
  /api/v1/agendas/{agendaId}/bloqueos:
    post:
      summary: Agrega bloqueo de agenda
      parameters:
        - name: agendaId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Aceptado
  /api/v1/agendas/{agendaId}/cupos/recalcular:
    post:
      summary: Recalcula cupos
      parameters:
        - name: agendaId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /api/v1/agendas/{agendaId}/disponibilidad:
    get:
      summary: Obtiene disponibilidad
      parameters:
        - name: agendaId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /fhir/Schedule:
    get:
      summary: FHIR Schedule search
      responses:
        '200':
          description: OK
  /fhir/Schedule/{id}:
    get:
      summary: FHIR Schedule read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /fhir/Slot:
    get:
      summary: FHIR Slot search
      responses:
        '200':
          description: OK
